src/Entity/Event.php
<?php

/*
 * This file is part of the vseth-semesterly-reports project.
 *
 * (c) Florian Moser <git@famoser.ch>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Entity\Base\BaseEntity;
use App\Entity\Traits\IdTrait;
use App\Entity\Traits\TimeTrait;
use App\Form\Type\SemesterType;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks
 */
class Event extends BaseEntity
{
    use IdTrait;
    use TimeTrait;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $semester;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $nameDe;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $nameEn;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptionDe;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptionEn;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     */
    private $location;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $startDate;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endDate;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default": true})
     */
    private $showInCalender = true;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $revenue = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $expenditure = 0;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $needFinancialSupport = false;

    /**
     * @var Organisation
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Organisation", inversedBy="events")
     */
    private $organisation;

    public function getSemester(): int
    {
        return $this->semester;
    }

    /**
     * @return int
     */
    public function getSemesterName(): string
    {
        return SemesterType::semesterToString($this->getSemester());
    }

    public function setSemester(int $semester): void
    {
        $this->semester = $semester;
    }

    /**
     * @return string|null
     */
    public function getName($preference = 'de')
    {
        if ($preference === 'de') {
            return $this->getNameDe() !== null ? $this->getNameDe() : $this->getNameEn();
        }

        return $this->getNameEn() !== null ? $this->getNameEn() : $this->getNameDe();
    }

    public function getNameDe(): ?string
    {
        return $this->nameDe;
    }

    public function setNameDe(?string $nameDe): void
    {
        $this->nameDe = $nameDe;
    }

    public function getNameEn(): ?string
    {
        return $this->nameEn;
    }

    public function setNameEn(?string $nameEn): void
    {
        $this->nameEn = $nameEn;
    }

    /**
     * @return string|null
     */
    public function getDescription($preference = 'de')
    {
        if ($preference === 'de') {
            return $this->getDescriptionDe() !== null ? $this->getDescriptionDe() : $this->getDescriptionEn();
        }

        return $this->getDescriptionEn() !== null ? $this->getDescriptionEn() : $this->getDescriptionDe();
    }

    public function getDescriptionDe(): ?string
    {
        return $this->descriptionDe;
    }

    public function setDescriptionDe(?string $descriptionDe): void
    {
        $this->descriptionDe = $descriptionDe;
    }

    public function getDescriptionEn(): ?string
    {
        return $this->descriptionEn;
    }

    public function setDescriptionEn(?string $descriptionEn): void
    {
        $this->descriptionEn = $descriptionEn;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): void
    {
        $this->location = $location;
    }

    public function getStartDate(): ?\DateTime
    {
        return $this->startDate;
    }

    public function setStartDate(?\DateTime $startDate): void
    {
        $this->startDate = $startDate;
    }

    public function getEndDate(): ?\DateTime
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTime $endDate): void
    {
        $this->endDate = $endDate;
    }

    public function getRevenue(): int
    {
        return $this->revenue;
    }

    public function setRevenue(int $revenue): void
    {
        $this->revenue = $revenue;
    }

    public function getExpenditure(): int
    {
        return $this->expenditure;
    }

    public function setExpenditure(int $expenditure): void
    {
        $this->expenditure = $expenditure;
    }

    public function isNeedFinancialSupport(): bool
    {
        return $this->needFinancialSupport;
    }

    public function setNeedFinancialSupport(bool $needFinancialSupport): void
    {
        $this->needFinancialSupport = $needFinancialSupport;
    }

    public function getOrganisation(): Organisation
    {
        return $this->organisation;
    }

    public function setOrganisation(Organisation $organisation): void
    {
        $this->organisation = $organisation;
    }

    public function getShowInCalender(): bool
    {
        return $this->showInCalender;
    }

    public function setShowInCalender(bool $showInCalender): void
    {
        $this->showInCalender = $showInCalender;
    }
}

templates/shared/tables.html.twig
{% macro events(organisation, showEditButtons = false, internalFields = false) %}
    {% if organisation.events|length == 0 %}
        <p>{{ "view.no_events_added_yet"|trans({}, "organisation") }}</p>
    {% else %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>{{ "semester"|trans({}, "entity_event") }}</th>
                <th>{{ "name"|trans({}, "entity_event") }}</th>
                {% if internalFields %}
                    <th>{{ "description"|trans({}, "entity_event") }}</th>
                    <th>{{ "start_date"|trans({}, "entity_event") }}</th>
                    <th>{{ "end_date"|trans({}, "entity_event") }}</th>
                {% endif %}
                <th>{{ "location"|trans({}, "entity_event") }}</th>
                {% if internalFields %}
                    <th>{{ "budget"|trans({}, "entity_event") }}</th>
                    <th>{{ "need_financial_support"|trans({}, "entity_event") }}</th>
                {% else %}
                    <th>{{ "start_date"|trans({}, "entity_event") }}</th>
                {% endif %}
                {% if showEditButtons %}
                    <th class="minimal-width"></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>

            {% for event in organisation.events %}
                <tr>
                    <td>{{ event.semesterName }}</td>
                    <td>{{ event.name }}</td>
                    {% if internalFields %}
                        <td>{{ event.description }}</td>
                        <td>{{ event.startDate|dateTimeFormat }}</td>
                        <td>{{ event.endDate|dateTimeFormat }}</td>
                    {% endif %}
                    <td>{{ event.location }}</td>
                    {% if internalFields %}
                        <td>+{{ event.revenue }} / -{{ event.expenditure }} </td>
                        <td>{{ event.needFinancialSupport|booleanFormat }}</td>
                    {% else %}
                        <td>{{ event.startDate|dateTimeFormat }}</td>
                    {% endif %}
                    {% if showEditButtons %}
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-light"
                                   href="{{ path("organisation_event_new", {"organisation" : organisation.id, "copy-id": event.id}) }}">
                                    <i class="fal fa-copy"></i>
                                </a>
                                <a class="btn btn-secondary"
                                   href="{{ path("organisation_event_edit", {"organisation" : organisation.id, "event": event.id}) }}">
                                    <i class="fal fa-pencil"></i>
                                </a>
                                <a class="btn btn-danger"
                                   href="{{ path("organisation_event_remove", {"organisation" : organisation.id, "event": event.id}) }}">
                                    <i class="fal fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endmacro %}

{% macro organisations(organisations) %}
    <table class="table table-striped sortable">
        <thead>
        <tr>
            <th class="minimal-width">{{ "relation_since_semester"|trans({}, "entity_organisation") }}</th>
            <th>{{ "name"|trans({}, "entity_organisation") }}</th>
            <th>{{ "login_url"|trans({}, "entity_organisation") }}</th>
            <th class="minimal-width"></th>
        </tr>
        </thead>
        <tbody>

        {% for organisation in organisations %}
            <tr>
                <td>{{ organisation.relationSinceSemester|semesterFormat }}</td>
                <td><a href="mailto:{{ organisation.email }}">{{ organisation.name }}</a></td>
                <td>
                    {{ path('login_code', { "code": organisation.authenticationCode}, true) }}
                    <a class="btn btn-outline-inverse btn-sm pl-2"
                       href="{{ path("administration_organisation_reset_authentication_code", {"organisation" : organisation.id}) }}">
                        <i class="fal fa-redo"></i>
                    </a>
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-secondary"
                           href="{{ path("administration_organisation_edit", {"organisation" : organisation.id}) }}">
                            <i class="fal fa-pencil"></i>
                        </a>
                        {% if organisation.hiddenAt is null %}
                            <a class="btn btn-warning"
                               href="{{ path("administration_organisation_hide", {"organisation" : organisation.id}) }}">
                                <i class="fal fa-eye-slash"></i>
                            </a>
                        {% else %}
                            <a class="btn btn-warning"
                               href="{{ path("administration_organisation_unhide", {"organisation" : organisation.id}) }}">
                                <i class="fal fa-eye"></i>
                            </a>
                        {% endif %}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}